name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
      - 'R4.2.3withoutQGIS'
    tags:
      - "v*"  # Trigger on version tags
  workflow_dispatch:  # Allow manual trigger for flexibility
    inputs:
      base_branch:
        description: "Branch to base the Docker image on (e.g., main, R4.2.3withoutQGIS)"
        required: true
        default: "main"

env:
  DOCKER_BUILDKIT: 1
  RENV_PATHS_ROOT: /root/.cache/R/renv

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 140

    steps:
      - name: Determine Base Branch
        id: base_branch
        run: |
          # Determine base branch
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "branch=${{ github.event.inputs.base_branch }}" >> $GITHUB_ENV
          else
            echo "branch=$(echo ${{ github.ref_name }} | grep -oP '^.*(?=/v)' || echo main)" >> $GITHUB_ENV
          fi

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}  # Dynamically use the selected branch

      - name: Calculate renv.lock hash
        id: renv_lock
        run: echo "renv_lock_hash=$(sha256sum renv.lock | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Calculate DOI.csv hash
        id: doi_csv
        run: echo "doi_csv_hash=$(sha256sum data/DOI.csv | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/firms-gta/shiny_compare_tunaatlas_datasests
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.url=${{ github.repository }}
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.title=GlobalTunaAtlasExplorer
            org.opencontainers.image.description=Interactive Shiny application for Tuna Atlas data visualization
            org.opencontainers.image.vendor=IRD
            org.opencontainers.image.author=Bastien Grasset <bastien.grasset@ird.fr>

      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master,network=host

      - name: Build Docker image
        run: |
          BRANCH_NAME=${{ env.branch }}
          docker buildx build \
            --progress=plain \
            --cache-from type=registry,ref=ghcr.io/firms-gta/shiny_compare_tunaatlas_datasests-cache:${BRANCH_NAME} \
            --cache-to type=registry,ref=ghcr.io/firms-gta/shiny_compare_tunaatlas_datasests-cache:${BRANCH_NAME},mode=max \
            --build-arg RENV_PATHS_ROOT=${{ env.RENV_PATHS_ROOT }} \
            --build-arg RENV_LOCK_HASH=${{ env.renv_lock_hash }} \
            --build-arg DOI_CSV_HASH=${{ env.doi_csv_hash }} \
            --tag ghcr.io/firms-gta/shiny_compare_tunaatlas_datasests:${BRANCH_NAME} \
            --tag ghcr.io/firms-gta/shiny_compare_tunaatlas_datasests:${{ github.ref_name }} \
            .

      - name: Push Docker image
        if: github.ref_type == 'tag'
        run: |
          docker push ghcr.io/firms-gta/shiny_compare_tunaatlas_datasests:${{ env.branch }}
          docker push ghcr.io/firms-gta/shiny_compare_tunaatlas_datasests:${{ github.ref_name }}
