name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
      - 'dev'
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Branch to base the Docker image on (e.g., main, dev)"
        required: true
        default: "main"
      target_tag:
        description: "Tag name for the Docker image (e.g., main, v1.0.0)"
        required: true
        default: "main"
      action:
        description: "Action to perform: build,build-and-push, build-no-cache-and-push"
        required: true
        default: "build"

env:
  CACHE_IMAGE: ghcr.io/firms-gta/shiny_compare_tunaatlas_datasests-cache
  DOCKER_BUILDKIT: 1
  RENV_PATHS_ROOT: ~/.cache/R/renv

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.base_branch }} # Utiliser la branche spécifiée dans l'input

      - name: Calculate renv.lock hash
        id: renv_lock
        run: |
          if [ -f renv.lock ]; then
            echo "renv_lock_hash=$(sha256sum renv.lock | cut -d' ' -f1)" >> $GITHUB_ENV
          else
            echo "renv_lock_hash=default" >> $GITHUB_ENV
          fi

      - name: Calculate DOI.csv hash
        id: doi_csv
        run: |
          if [ -f DOI.csv ]; then
            echo "doi_csv_hash=$(sha256sum DOI.csv | cut -d' ' -f1)" >> $GITHUB_ENV
          else
            echo "doi_csv_hash=default" >> $GITHUB_ENV
          fi

      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          BASE_BRANCH="${{ github.event.inputs.base_branch }}"
          TARGET_TAG="${{ github.event.inputs.target_tag }}"
          echo "Building Docker image from branch '${BASE_BRANCH}' and tagging it as '${TARGET_TAG}'..."
          
          docker buildx build \
            --progress=plain \
            --cache-from type=registry,ref=${{ env.CACHE_IMAGE }}:${BASE_BRANCH} \
            --cache-to type=registry,ref=${{ env.CACHE_IMAGE }}:${BASE_BRANCH},mode=max \
            --build-arg RENV_PATHS_ROOT=${{ env.RENV_PATHS_ROOT }} \
            --build-arg RENV_LOCK_HASH=${{ env.renv_lock_hash }} \
            --build-arg DOI_CSV_HASH=${{ env.doi_csv_hash }} \
            --tag ghcr.io/firms-gta/shiny_compare_tunaatlas_datasests:${TARGET_TAG} \
            --push \
            .
